from proto_topy.entities import ProtoDict, ProtoModule, CompilationFailed
import pytest
import os
from pathlib import Path
from distutils.spawn import find_executable

protoc_path = Path(find_executable("protoc") or os.environ.get('PROTOC'))


def test_add_proto():
    proto = ProtoModule(file_path="test.proto", content="")
    proto_dict = ProtoDict(compiler_path=protoc_path)
    proto_dict.add_proto(proto)
    assert "test.proto" in proto_dict.protos


def test_add_proto2():
    proto_dict = ProtoDict(protoc_path, *(ProtoModule(file_path="test1.proto", content=""),
                                          ProtoModule(file_path="test2.proto", content="")),)
    assert "test1.proto" in proto_dict.protos
    assert "test2.proto" in proto_dict.protos


def test_bad_protoc():
    with pytest.raises(FileNotFoundError):
        proto_dict = ProtoDict(Path('dummy'))
        proto_dict.compile()


def test_no_protoc():
    with pytest.raises(TypeError):
        ProtoDict()


def test_compile_wrong_proto():
    proto_dict = ProtoDict(protoc_path, ProtoModule(file_path="test.proto", content=""))
    with pytest.raises(CompilationFailed):
        proto_dict.compile()


def test_compile_minimal_proto():
    module_name = "test"
    proto = ProtoModule(file_path=f"{module_name}.proto", content="""
    syntax = "proto3";
    import "google/protobuf/timestamp.proto";
    message test {
        google.protobuf.Timestamp created = 1;
    }
    """)
    proto_dict = ProtoDict(protoc_path, proto)
    proto_dict.compile()
    assert "\n".join(proto.module_source.split("\n")[:4]) == '''# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""'''


def test_compile_missing_dependency():
    proto = ProtoModule(file_path="test.proto", content="""
    syntax = "proto3";
    import "other.proto";
    """)
    proto_dict = ProtoDict(protoc_path, proto)
    with pytest.raises(CompilationFailed, match=r'other.proto: File not found.*'):
        proto_dict.compile()


def _test_compile_simple_dependency():
    proto = ProtoModule(file_path="test.proto", content="""
    syntax = "proto3";
    import "other.proto";
    """)
    other_proto = ProtoModule(file_path="other.proto", content='syntax = "proto3";')
    proto_dict = ProtoDict(protoc_path, proto, other_proto)
    proto_dict.compile()
