from proto_topy.entities import ProtoModules, ProtoModule, CompilationFailed
import pytest
import os
import sys
from pathlib import Path
from distutils.spawn import find_executable

protoc_path = Path(find_executable("protoc") or os.environ.get('PROTOC'))


def test_add_proto():
    proto = ProtoModule(file_path=Path("test1.proto"), content="")
    modules = ProtoModules(compiler_path=protoc_path)
    modules.add_proto(proto)
    assert Path("test1.proto") in modules.protos


def test_add_proto2():
    modules = ProtoModules(protoc_path, *(ProtoModule(file_path=Path("test2.proto"), content=""),
                                             ProtoModule(file_path=Path("test3.proto"), content="")), )
    assert Path("test2.proto") in modules.protos
    assert Path("test3.proto") in modules.protos


def test_bad_protoc():
    with pytest.raises(FileNotFoundError):
        modules = ProtoModules(Path('dummy'))
        modules.compile()


def test_no_protoc():
    with pytest.raises(TypeError):
        ProtoModules()


def test_compile_wrong_proto():
    modules = ProtoModules(protoc_path, ProtoModule(file_path=Path("test4.proto"), content=""))
    with pytest.raises(CompilationFailed):
        modules.compile()


def test_compile_minimal_proto():
    from google.protobuf.timestamp_pb2 import Timestamp

    proto = ProtoModule(file_path=Path("test5.proto"), content="""
    syntax = "proto3";
    import "google/protobuf/timestamp.proto";
    message Test5 {
        google.protobuf.Timestamp created = 1;
    }
    """)
    modules = ProtoModules(protoc_path, proto)
    modules.compile()
    sys.modules["test5"] = proto.module
    atest5 = proto.module.Test5()
    assert isinstance(atest5.created, Timestamp)
    del sys.modules["test5"]


def test_compile_minimal_proto_in_a_package():
    from google.protobuf.timestamp_pb2 import Timestamp
    proto = ProtoModule(file_path=Path("p1/p2/p3/thing.proto"), content="""
    syntax = "proto3";
    import "google/protobuf/timestamp.proto";
    message Thing {
        google.protobuf.Timestamp created = 1;
    }
    """)
    modules = ProtoModules(protoc_path, proto)
    modules.compile()
    assert "\n".join(proto.module_source.split("\n")[:4]) == '''# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p1/p2/p3/thing.proto
"""Generated protocol buffer code."""'''
    sys.modules["thing"] = proto.module
    athing = proto.module.Thing()
    assert isinstance(athing.created, Timestamp)


def test_compile_missing_dependency():
    proto = ProtoModule(file_path=Path("test.proto"), content="""
    syntax = "proto3";
    import "other.proto";
    """)
    modules = ProtoModules(protoc_path, proto)
    with pytest.raises(CompilationFailed, match=r'other.proto: File not found.*'):
        modules.compile()


def test_compile_ununsed_dependency():
    proto = ProtoModule(file_path=Path("test.proto"), content="""
    syntax = "proto3";
    import "other.proto";
    """)
    other_proto = ProtoModule(file_path=Path("other.proto"), content="""
    syntax = "proto3";
    import "google/protobuf/timestamp.proto";
    message OtherThing {
        google.protobuf.Timestamp created = 1;
    }
    """)
    modules = ProtoModules(protoc_path, proto, other_proto)
    modules.compile()


def test_compile_simple_dependency():
    from google.protobuf.timestamp_pb2 import Timestamp
    proto = ProtoModule(file_path=Path("p3/p4/test6.proto"), content="""
    syntax = "proto3";
    import "p1/p2/other2.proto";
    message Test6 {
        OtherThing2 foo = 1;
    };
    """)
    other_proto = ProtoModule(file_path=Path("p1/p2/other2.proto"), content="""
    syntax = "proto3";
    import "google/protobuf/timestamp.proto";
    message OtherThing2 {
        google.protobuf.Timestamp created = 1;
    }
    """)
    modules = ProtoModules(protoc_path, proto, other_proto)
    modules.compile()
    sys.modules.update({proto.name: proto.module for proto in modules.protos.values()})
    atest6 = modules.protos[Path("p3/p4/test6.proto")].module.Test6()
    assert isinstance(atest6.foo.created, Timestamp)
    for proto in modules.protos.values():
        del sys.modules[proto.name]
