name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
        # , macos-latest, windows-latest]
        os: [ubuntu-latest]
        # , '3.9', '3.10', '3.11', '3.12']
        python: ['3.8']
        # ['21.12', '23.x'] ??
        protoc: ['25.x']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      # https://github.com/actions/setup-python
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
        cache: pip
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      # https://github.com/arduino/setup-protoc
      with:
        version: ${{ matrix.protoc }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        pip --version
        tox --version
        pip list --format=freeze
        protoc --version
    - name: Setup test suite
      run: tox -vv --notest
    - name: Run test suite
      run: tox --skip-pkg-install

